// ReversiEngine.h

#ifndef REVERSI_ENGINE
#define REVERSI_ENGINE

#define ID_STONE_NONE	0
#define ID_STONE_BLACK	1
#define ID_STONE_WHITE	2

#define GAME_STATUS_NORMAL	0
#define GAME_STATUS_END		1
#define GAME_STATUS_BLACK_PASS	2
#define GAME_STATUS_WHITE_PASS	3
#define GAME_STATUS_BLACK_PUT	4
#define GAME_STATUS_WHITE_PUT	5

#define GAME_TURN_WHITE	1
#define GAME_TURN_BLACK	0

#endif

